version: '2'
volumes:
  landscape-config: {}
  landscape-data: {}
  landscape-ssl: {}
  postgres-data: {}
services:

  rabbitmq:
    platform: linux/amd64
    image: rabbitmq:3.7.14-management
    hostname: rabbitmq

  server:
    build: server
    hostname: server # must match crt for use by landscape-config
    depends_on:
      postgres:
        condition: service_started
      rabbitmq:
        condition: service_started
    ports:
     - "80:80"
     - "443:443"
    environment:
      DB_HOST: postgres
      DB_LANDSCAPE_PASS: password
      DB_PASS: password
      DB_PORT: '5432'
      DB_USER: postgres
      INITIALIZE_SCHEMA: 'yes'
      UPGRADE_SCHEMA: 'yes'
      RMQ_HOST: rabbitmq
      STARTUP_WAIT_TIME: '15'
      SMTP_HOST: yourstmpserver
      SMTP_PORT: '587'
      SMTP_USER: user@mail.lan
      SMTP_FROM: landscape-demo@yourdomain.lan
      SMTP_PASS: password
      SMTP_TLS: 'yes'
      SMTP_AUTH: 'yes'
      SMTP_DOMAIN: yourdomain.lan
    volumes:
    - landscape-config:/etc/landscape
    - landscape-data:/var/lib/landscape
    - landscape-ssl:/etc/ssl
    - ./server/assets/ldap.conf:/opt/canonical/ldap/etc/ldap.conf
    - ./server/assets/apache-landscape.conf:/etc/apache2/sites-available/landscape.conf
    - ./server/assets/entrypoint.sh:/sbin/entrypoint.sh

  postgres:
    build: postgres
    hostname: postgres
    environment:
      POSTGRES_PASSWORD: password
    volumes:
    - postgres-data:/var/lib/postgresql/data

  s6demo:
    build: s6demo
    hostname: s6demo
    volumes:
      - ./server/assets/certs/landscape_server.pem:/etc/ssl/certs/landscape_server.pem
